// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdJ3-BKtl6GekBO664a-xxqeWqk5_CsZ4',
    appId: '1:812104653331:web:14a3b227998e9927a0fde6',
    messagingSenderId: '812104653331',
    projectId: 'daos-15254',
    authDomain: 'daos-15254.firebaseapp.com',
    storageBucket: 'daos-15254.firebasestorage.app',
    measurementId: 'G-09PB4ZV27C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDB1Y60_izwu9Z_YXe1z6Mc5J6LoEmpUbo',
    appId: '1:812104653331:android:cb0eea039a45c2e5a0fde6',
    messagingSenderId: '812104653331',
    projectId: 'daos-15254',
    storageBucket: 'daos-15254.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiMRv0qR3Eq0homX4sTpBS6EgkUxBufNU',
    appId: '1:812104653331:ios:17ebc3a196fb0519a0fde6',
    messagingSenderId: '812104653331',
    projectId: 'daos-15254',
    storageBucket: 'daos-15254.firebasestorage.app',
    iosBundleId: 'com.taskmail.taskmail',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiMRv0qR3Eq0homX4sTpBS6EgkUxBufNU',
    appId: '1:812104653331:ios:17ebc3a196fb0519a0fde6',
    messagingSenderId: '812104653331',
    projectId: 'daos-15254',
    storageBucket: 'daos-15254.firebasestorage.app',
    iosBundleId: 'com.taskmail.taskmail',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdJ3-BKtl6GekBO664a-xxqeWqk5_CsZ4',
    appId: '1:812104653331:web:5ec112b6815cb32da0fde6',
    messagingSenderId: '812104653331',
    projectId: 'daos-15254',
    authDomain: 'daos-15254.firebaseapp.com',
    storageBucket: 'daos-15254.firebasestorage.app',
    measurementId: 'G-47RVFQ289C',
  );
}
